### PR TITLE
Read me updated

### PR DESCRIPTION
**Pull request by Joe-houghton**
Read me updated after being emailed questions regarding using multiple devices.

Feel free to double check that this makes sense

### CODE REVIEW

**Comment by leachj** [comment]
Thanks. Makes a lot more sense now. I'm never very good at writing documentation!

**Comment by leachj** [comment]
If you want to make any more changes Joe I'm happy to give you push access to the repo. I don't really work with my lightwaverf stuff that much any more

**Comment by Joe-houghton** [comment]
Hi leach,

yeah that would be good. I'm currently playing around with it, domoticz, OK google and alexa for home automation.

Thanks,

Joe

**Comment by leachj** [comment]
I've added you. Sounds like your interests are similar to mine. I look forward to seeing more of your work.

**Pull request merged**
